name: Github Auto Deploy

on: push

env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  # YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  # YOUTUBE_API_KEY2: ${{ secrets.YOUTUBE_API_KEY2 }}
  # YOUTUBE_API_KEY3: ${{ secrets.YOUTUBE_API_KEY3 }}
  # YOUTUBE_API_KEY4: ${{ secrets.YOUTUBE_API_KEY4 }}
  # YOUTUBE_API_KEY5: ${{ secrets.YOUTUBE_API_KEY5 }}
  # YOUTUBE_API_KEY6: ${{ secrets.YOUTUBE_API_KEY6 }}
  # GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
